-- Seed data: 12 example agents for a populated directory
-- Run after 001_initial_schema.sql

INSERT INTO agents (slug, name, tagline, description, owner_id, owner_name, owner_url, version, status, capabilities, categories, a2a_endpoint, mcp_server_url, api_endpoint, docs_url, protocols, input_formats, output_formats, is_verified, trust_score, total_lookups, pricing_model, pricing_details, tags, metadata) VALUES

('legal-analyzer-pro', 'Legal Analyzer Pro', 'Contract review and legal document analysis', 'Analyzes legal documents including contracts, NDAs, and terms of service. Identifies key clauses, potential risks, and provides plain-language summaries. Supports comparison between document versions.', 'seed-user-1', 'LegalTech Labs', 'https://github.com/legaltechlabs', '2.1.0', 'active', '{contract-review,legal-analysis,document-summarization,risk-assessment}', '{legal}', 'https://legal-analyzer.example.com/.well-known/agent.json', NULL, 'https://api.legal-analyzer.example.com/v1', 'https://docs.legal-analyzer.example.com', '{a2a,rest}', '{text,json,pdf}', '{text,json,markdown}', true, 0.92, 12847, 'per-task', '$0.05 per page analyzed', '{ai,nlp,legal-tech,document-processing}', '{"model": "claude-sonnet-4-5", "framework": "langchain", "avg_response_time_ms": 1200}'),

('code-review-bot', 'CodeReview Bot', 'Automated code review with security and performance analysis', 'Reviews pull requests and code changes for bugs, security vulnerabilities, performance issues, and style violations. Supports 15+ programming languages. Integrates with GitHub and GitLab.', 'seed-user-2', 'DevTools Inc', 'https://github.com/devtoolsinc', '3.0.1', 'active', '{code-review,security-analysis,bug-detection,performance-optimization}', '{engineering}', NULL, 'https://mcp.codereview.example.com', 'https://api.codereview.example.com/v2', 'https://codereview.example.com/docs', '{mcp,rest}', '{text,json}', '{text,json,markdown}', true, 0.88, 8432, 'subscription', '$29/mo for teams, free for open source', '{developer-tools,code-quality,ci-cd,security}', '{"model": "claude-opus-4-5", "supported_languages": ["python", "typescript", "go", "rust", "java"]}'),

('data-pipeline-agent', 'DataPipe', 'ETL pipeline orchestration and data transformation', 'Designs, builds, and monitors data pipelines. Handles schema inference, data quality checks, and automated transformations. Connects to 50+ data sources.', 'seed-user-3', 'DataFlow Systems', 'https://github.com/dataflowsys', '1.5.0', 'active', '{etl,data-transformation,pipeline-orchestration,schema-inference}', '{data,engineering}', 'https://datapipe.example.com/.well-known/agent.json', NULL, 'https://api.datapipe.example.com/v1', 'https://docs.datapipe.example.com', '{a2a,rest,websocket}', '{json,text}', '{json,text}', false, 0.71, 3219, 'usage-based', '$0.001 per record processed', '{data-engineering,etl,automation,big-data}', '{"framework": "apache-airflow", "connectors": 52}'),

('translate-ai', 'TranslateAI', 'Real-time multilingual translation with context awareness', 'Translates text between 100+ languages with context-aware accuracy. Handles domain-specific terminology, preserves formatting, and supports batch processing. Optimized for technical and legal documents.', 'seed-user-4', 'Polyglot AI', 'https://github.com/polyglotai', '4.2.0', 'active', '{translation,localization,language-detection,terminology-management}', '{content}', 'https://translate-ai.example.com/.well-known/agent.json', 'https://mcp.translate-ai.example.com', 'https://api.translate-ai.example.com/v3', 'https://docs.translate-ai.example.com', '{a2a,mcp,rest}', '{text,json,pdf}', '{text,json,markdown,pdf}', true, 0.95, 45210, 'usage-based', '$0.002 per 1000 characters', '{translation,nlp,multilingual,i18n}', '{"languages": 107, "model": "custom-mt-v4"}'),

('customer-support-ai', 'SupportBot', 'Intelligent customer support with ticket routing and resolution', 'Handles customer inquiries via chat and email. Routes complex issues to human agents, resolves common questions automatically, and provides sentiment analysis for quality monitoring.', 'seed-user-5', 'CX Solutions', 'https://github.com/cxsolutions', '2.0.0', 'active', '{customer-support,ticket-routing,sentiment-analysis,faq-resolution}', '{support}', NULL, NULL, 'https://api.supportbot.example.com/v2', 'https://docs.supportbot.example.com', '{rest}', '{text,json}', '{text,json}', false, 0.63, 1876, 'subscription', '$99/mo per seat', '{customer-service,chatbot,automation,helpdesk}', '{"model": "claude-haiku-4-5", "avg_resolution_time_min": 2.3}'),

('financial-analyst', 'FinAnalyst', 'Financial data analysis and reporting', 'Analyzes financial statements, market data, and economic indicators. Generates investment reports, risk assessments, and trend forecasts. SEC filing parsing and ESG scoring.', 'seed-user-6', 'Quant Works', 'https://github.com/quantworks', '1.8.0', 'active', '{financial-analysis,market-research,risk-assessment,report-generation}', '{finance}', 'https://finanalyst.example.com/.well-known/agent.json', NULL, 'https://api.finanalyst.example.com/v1', 'https://docs.finanalyst.example.com', '{a2a,rest}', '{text,json,pdf}', '{text,json,markdown,pdf}', true, 0.85, 6543, 'per-task', '$0.10 per analysis', '{finance,analytics,investing,market-data}', '{"data_sources": ["sec-edgar", "yahoo-finance", "bloomberg"], "model": "claude-sonnet-4-5"}'),

('image-describer', 'VisionAI', 'Image analysis, captioning, and visual question answering', 'Analyzes images to generate detailed descriptions, extract text (OCR), identify objects and scenes, and answer questions about visual content. Supports batch processing of image libraries.', 'seed-user-7', 'Visual Intelligence Co', 'https://github.com/visualintel', '2.3.0', 'active', '{image-analysis,ocr,visual-qa,image-captioning}', '{content,data}', NULL, 'https://mcp.visionai.example.com', 'https://api.visionai.example.com/v2', 'https://docs.visionai.example.com', '{mcp,rest}', '{image,json,text}', '{text,json,markdown}', false, 0.74, 4120, 'usage-based', '$0.003 per image', '{computer-vision,ocr,image-processing,multimodal}', '{"model": "claude-sonnet-4-5", "supported_formats": ["png", "jpg", "webp", "gif"]}'),

('sales-outreach-ai', 'OutreachPro', 'Personalized sales outreach and lead qualification', 'Generates personalized outreach emails, qualifies leads based on ICP criteria, and manages follow-up sequences. Integrates with CRM systems and enrichment APIs.', 'seed-user-8', 'SalesFlow AI', 'https://github.com/salesflowai', '1.2.0', 'active', '{lead-qualification,email-generation,crm-integration,sales-automation}', '{sales}', NULL, NULL, 'https://api.outreachpro.example.com/v1', 'https://docs.outreachpro.example.com', '{rest}', '{text,json}', '{text,json}', false, 0.58, 982, 'subscription', '$49/mo per user', '{sales,marketing,email,crm}', '{"integrations": ["salesforce", "hubspot", "pipedrive"]}'),

('medical-research-ai', 'MedSearch', 'Medical literature search and evidence synthesis', 'Searches PubMed and clinical trial databases to synthesize evidence for clinical questions. Generates structured summaries with evidence quality ratings. HIPAA-aware processing.', 'seed-user-9', 'HealthAI Research', 'https://github.com/healthai', '1.0.0', 'active', '{literature-review,evidence-synthesis,clinical-qa,medical-research}', '{healthcare}', 'https://medsearch.example.com/.well-known/agent.json', NULL, 'https://api.medsearch.example.com/v1', 'https://docs.medsearch.example.com', '{a2a,rest}', '{text,json}', '{text,json,markdown}', true, 0.91, 7891, 'free', 'Free for researchers, institutional licensing available', '{healthcare,medical,research,pubmed}', '{"databases": ["pubmed", "clinicaltrials-gov", "cochrane"], "hipaa_compliant": true}'),

('security-scanner', 'SecScan', 'Application security scanning and vulnerability detection', 'Scans web applications and APIs for security vulnerabilities including OWASP Top 10, misconfigurations, and dependency risks. Provides remediation guidance with code examples.', 'seed-user-10', 'CyberGuard AI', 'https://github.com/cyberguardai', '3.1.0', 'active', '{vulnerability-scanning,security-audit,dependency-check,penetration-testing}', '{security,engineering}', NULL, 'https://mcp.secscan.example.com', 'https://api.secscan.example.com/v3', 'https://docs.secscan.example.com', '{mcp,rest}', '{text,json}', '{text,json,markdown}', true, 0.89, 5678, 'per-task', '$1 per scan', '{security,appsec,vulnerability,devsecops}', '{"scan_types": ["sast", "dast", "sca"], "frameworks": ["owasp-top10", "cwe"]}'),

('content-writer', 'WriteFlow', 'AI content writing with brand voice consistency', 'Generates blog posts, marketing copy, and social media content. Learns brand voice from examples, supports SEO optimization, and handles content calendars. Multi-format output.', 'seed-user-11', 'ContentAI Studio', 'https://github.com/contentaistudio', '2.0.0', 'active', '{content-writing,seo-optimization,brand-voice,copywriting}', '{content,sales}', NULL, NULL, 'https://api.writeflow.example.com/v2', 'https://docs.writeflow.example.com', '{rest,graphql}', '{text,json}', '{text,json,markdown}', false, 0.67, 2345, 'subscription', '$19/mo for 50K words', '{content,writing,seo,marketing}', '{"model": "claude-sonnet-4-5", "max_output_tokens": 8000}'),

('edu-tutor', 'TutorAI', 'Adaptive educational tutoring across STEM subjects', 'Provides personalized tutoring with adaptive difficulty, step-by-step explanations, and practice problems. Tracks student progress and identifies knowledge gaps. K-12 and university level.', 'seed-user-12', 'EduTech AI', 'https://github.com/edutechai', '1.4.0', 'active', '{tutoring,adaptive-learning,problem-generation,progress-tracking}', '{education}', 'https://tutorai.example.com/.well-known/agent.json', 'https://mcp.tutorai.example.com', 'https://api.tutorai.example.com/v1', 'https://docs.tutorai.example.com', '{a2a,mcp,rest}', '{text,json,image}', '{text,json,markdown}', false, 0.76, 3890, 'free', 'Free for students, school licensing available', '{education,tutoring,stem,adaptive-learning}', '{"subjects": ["math", "physics", "chemistry", "biology", "cs"], "levels": ["k12", "university"]}');
